apiVersion: webbrowser.cloud/v1
kind: Cluster
metadata:
  name: sample
  namespace: web-browser-cloud-sample
spec:
  image: ghcr.io/webbrowsercloud/webbrowsercloud-cluster:1.3.8
  worker:
    image: browserless/chrome:1.54.0-chrome-stable
#    resources:
#      requests:
#        cpu: 500m
#        memory: 0.5Gi
#      limits:
#        cpu: 500m
#        memory: 0.5Gi
    autoscaling:
      minReplicas: 1
      maxReplicas: 3
  userDataStorageSize: 100Gi
  workspaceStorageSize: 100Gi
  domains:
    - "sample.webbrowser.cloud"